### ISSUE TITLE
[Bug]: 设置页点击下方代码发布页的外链后，设置页本身也会变成仓库网页，并显示异常

### ISSUE THREAD

**Issue by lucienshawls** [SoraNoNeko/cpu_net#1]
Tag: v1.2.2
这是登录页的正常界面
<img width="441" alt="image" src="https://github.com/SoraNoNeko/cpu_net/assets/82591976/30110598-979b-4be2-9789-2b6aef2af97c">
这是点击代码发布页后的界面
<img width="441" alt="image" src="https://github.com/SoraNoNeko/cpu_net/assets/82591976/1f3c4e77-9b05-4441-aa6c-2adb5a7c79a4">
可以看到软件在窗口内打开了该Github仓库网页，并且加载不正常。点击主页后再点击设置就会恢复正常。
猜测是软件使用了加载html文档的方式加载界面，点击链接就会跳转。

**Comment by lucienshawls** [comment]
考虑到主页上也有通过浏览器打开链接的按钮（教程、宽带账号绑定），这应该是有办法修复的。

**Comment by lucienshawls** [comment]
问题追加：在点击代码发布页导致设置页面跳转后，点主页再点回设置，发现程序无法自动载入之前保存的密码字段，只能重启软件解决。

**Comment by SoraNoNeko** [comment]
该问题已在代码中修复，准备多修几个bug一起编译发release

**Comment by lucienshawls** [comment]
有个不知是否相关的问题（可能和上面的“问题追加”有关系）：点击设置页的取消按钮，会清空学号、密码和运营商的选择状态，并且点主页再点回设置也仍然是清空状态（Config.json文件没有被修改）。我觉得更好的逻辑是，点取消时应该加载此时Config.json文件内的设置（相当于撤销修改，恢复上一次设置）。

**Comment by SoraNoNeko** [comment]
不错的想法，1.3发布的时候采用，现在的发布一版修复过的版本先

**Comment by lucienshawls** [comment]
我交个新的issue，方便你追踪

**Comment by SoraNoNeko** [comment]
最新版本问题已修复
