### ISSUE TITLE
[Bug]: 双击托盘图标或右击托盘图标后点击显示窗口时，会在任务栏显示软件图标，但是软件并未前台显示

### ISSUE THREAD

**Issue by lucienshawls** [SoraNoNeko/cpu_net#3]
Tag: v1.2.2
如题，最小化窗口后，应用的任务栏图标正常消失并回到托盘区，但是双击托盘图标或右击图标并点击显示窗口后，任务栏显示了图标而窗口没有显示，必须点击一下任务栏图标才能显示窗口。
<img width="521" alt="image" src="https://github.com/SoraNoNeko/cpu_net/assets/82591976/e953c8b5-ee22-4dbe-b387-c3e321fcf4fe">

**Comment by lucienshawls** [comment]
问题修正：只有点击正常显示的窗口右上角的最小化按钮使软件最小化后，才会出现此问题。如果之前是在托盘区点击了隐藏窗口，那么不论是双击托盘图标或右击托盘图标后点击显示窗口，窗口均会正常显示。

**Comment by SoraNoNeko** [comment]
这个是C#的一个焦点获取问题，有点复杂，做的时候我没完全搞明白，因为不影响正常使用就没有修

**Comment by SoraNoNeko** [comment]
1.3.0已修复
