### ISSUE TITLE
[Bug]: 开机自启功能只有添加或删除启动项操作，缺少是否已启用判定

### ISSUE THREAD

**Issue by lucienshawls** [SoraNoNeko/cpu_net#4]
Tag: v1.2.2
当勾选开机启动复选框时，正常添加了启动项：
<img width="703" alt="image" src="https://github.com/SoraNoNeko/cpu_net/assets/82591976/3a1f36c7-01e7-40c0-915e-1f4b5b488853">
取消勾选时也能正常删除启动项。
但是，在任务管理器中手动禁用该程序的启动项，再在软件中取消勾选再勾选开机启动复选框后，程序仅能添加一个被禁用了的启动项，没能自动启用。
<img width="516" alt="image" src="https://github.com/SoraNoNeko/cpu_net/assets/82591976/254347e0-3682-4530-a81f-a8573695d5a3">
经过测试，其它部分软件可以在用户于任务管理器手动禁用启动项的情况下，在软件内刷新自启状态后正常使得应用自启，用户手动的禁用操作被覆盖，说明这是可以做到的操作。
猜测是本软件只添加启动项，而没有判断该启动项的启用/禁用状态。

**Comment by SoraNoNeko** [comment]
研究了一下，要判断是否已启用得去修改注册表，需要管理员权限，我需要尽量避免这种操作，而且该软件面向的用户大部分都不会去在启动应用里进行禁用，他们需要学会的是如何加入杀毒软件的白名单

**Comment by lucienshawls** [comment]
是否可以临时提权？就是在进行这个操作的时候临时请求管理员权限，程序本身运行不要求高权限。毕竟开机自启功能要求管理员权限也是很正常的请求。

**Comment by SoraNoNeko** [comment]
避免的操作是去操作注册表。我写的也不是啥流氓软件，也并不需要这么高的权限。
同时我也无法理解在软件中启用又在开始菜单中禁用的操作，这在我看来属实很蠢。

**Comment by lucienshawls** [comment]
哈哈，这个操作确实不同寻常，但是也确实会有顾客在酒吧点炒饭:-D
