### ISSUE TITLE
[Bug]: 账户信息设置中，运营商选择状态判断的逻辑错误，或提示表述有误

### ISSUE THREAD

**Issue by lucienshawls** [SoraNoNeko/cpu_net#5]
Tag: v1.2.2
<img width="436" alt="image" src="https://github.com/SoraNoNeko/cpu_net/assets/82591976/b7784fcb-8120-4ab1-8b7b-19a7637564cf">
如图，软件提供了三种登录模式，我猜测宽带指的是宿舍宽带登录，CPU指的是教学区域CPU无线网或教学区域连接网线时登录，而自动指的是软件自动判断设备处于何种环境并登录。
如果我猜测有误，那软件在此处的提示表述容易造成误解，需要更正。
如果我猜测无误，那么考虑到CPU模式不需要账号的运营商信息，软件理应允许用户不选择运营商，但是不选择运营商却无法保存设置，那这就是运营商选择状态判断的逻辑错误，需要修正。

**Comment by SoraNoNeko** [comment]
最新版已修改
