### ISSUE TITLE
[Bug]: 右击托盘图标退出时，短暂地出现了确认退出的窗口，随后该窗口立即消失，程序退出

### ISSUE THREAD

**Issue by lucienshawls** [SoraNoNeko/cpu_net#8]
Tag: v1.2.2
如图，当用户右击该程序的托盘图标并点击退出后，屏幕中央弹出了一个退出确认窗口（消失速度太快难以截图），但是立即退出了。
![image](https://github.com/SoraNoNeko/cpu_net/assets/82591976/8f0e2823-214d-4ccc-9c1d-8b5f6d023f35)
一般情况下，当用户点击退出程序后，程序要么直接退出，要么弹出对话框询问是否确认退出，一般不会先弹出一个对话框然后不理会用户立即退出，建议修复。
猜测是程序检测窗口即将被关闭时会弹出对话框，但是在托盘图标那里点击退出的优先级太高，导致程序先触发窗口关闭事件弹出对话框，紧接着程序被强制退出。

**Comment by SoraNoNeko** [comment]
这个是已知bug，能力有限暂时还修不了，因为不影响正常使用所以优先级比较低，不过还是感谢反馈

**Comment by SoraNoNeko** [comment]
1.3.0已修复
