### ISSUE TITLE
[Feature Request]: 添加主页和设置页面在一定条件下自动跳转的功能

### ISSUE THREAD

**Issue by lucienshawls** [SoraNoNeko/cpu_net#9]
希望添加两个功能：
1. 在设置页点击保存设置的确认对话框后，直接跳转到主页以供连接，不需要用户手动点击切换了。原因是，用户保存设置后，短时间内一般不需要用到设置页面且通常需要到主页界面连接上网；
2. 在主页点击登录按钮后，如果检测不到配置文件或配置有误就自动跳转到设置页。原因是，对第一次使用的人来说，主页和设置页两个按钮不够显眼，用户可能会认为点击登录按钮后会弹出对话框要求输入信息，点击后程序报错，那么用户就可能需要花几秒钟找设置的位置。自动跳转可以一定程度上优化体验。

**Comment by SoraNoNeko** [comment]
可以

**Comment by SoraNoNeko** [comment]
爆了，这段逻辑写起来比想象的麻烦多了，窗口的线程进不到主线程改不了页面切换的状态

**Comment by SoraNoNeko** [comment]
1.3.1版本已添加
